stages:
  - build
  - push

variables:
  IMAGE_NAME: ghcr.io/${CI_PROJECT_NAMESPACE}/${CI_PROJECT_NAME}:$CI_COMMIT_REF_SLUG

before_script:
  - echo "$GITHUB_TOKEN" | docker login ghcr.io -u "$GITHUB_USERNAME" --password-stdin

build:
  stage: build
  script:
    - docker build -t $IMAGE_NAME .
  only:
    - branches

push:
  stage: push
  script:
    - docker push $IMAGE_NAME
  only:
    - branches